### ISSUE TITLE
Building fails on Xubuntu 15.04

### ISSUE THREAD

**Issue by moobsen** [cygnusxi/CurecoinSource#2]
I tried to build the wallet as described in the readme, but the first issue was:

> Package libdb5.1++-dev is not available, but is referred to by another package.

So I just installed libdb5.3++-dev. *qmake* gives me a few Warnings, but nothing critical as far as I can tell. *make* just fails with this:

/bin/sh share/genbuild.sh /home/mo/src/CurecoinSource/build/build.h
g++ -c -m64 -pipe -fstack-protector-all --param ssp-buffer-size=1 -msse2 -O2 -fdiagnostics-show-option -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -Wstack-protector -D_REENTRANT -fPIE -DQT_GUI -DBOOST_THREAD_USE_LIB -DBOOST_SPIRIT_THREADSAFE -DBOOST_THREAD_PROVIDES_GENERIC_SHARED_MUTEX_ON_WIN -D__NO_SYSTEM_INCLUDES -DUSE_UPNP=1 -DSTATICLIB -DUSE_IPV6=1 -DHAVE_BUILD_INFO -DLINUX -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -Isrc -Isrc/json -Isrc/qt -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -Ibuild -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -o build/curecoin.o src/qt/curecoin.cpp
In file included from src/qt/curecoin.cpp:4:0:
src/qt/curecoingui.h:4:23: fatal error: QMainWindow: No such file or directory
 #include <QMainWindow>
                       ^
compilation terminated.
Makefile:1026: recipe for target 'build/curecoin.o' failed

Any ideas?

**Comment by cygnusxi** [comment]
Did you try qt4 and other dependencies? Try : 

sudo apt-get install qt4-qmake libqt4-dev libboost-dev libboost-system-dev libboost-filesystem-dev libboost-program-options-dev libboost-thread-dev libssl-dev libminiupnpc-dev libdb5.3++-dev dh-make build-essential

**Comment by moobsen** [comment]
That did the trick. I guess I should not have used --no-install-recommends, as it says in the README.

Thanks!
