### ISSUE TITLE
Avast threat detected

### ISSUE THREAD

**Issue by DiseaseG** [cygnusxi/CurecoinSource#20]
So today I tried  opening my  curecoin wallet and the antivirus reported a threat and removed the exe. So now I tried installing it again downloaded the new one. When I clicked to install, Avast again reported a threat detected. Is this a false positive something. Would really like an answer.

**Comment by gsxryan** [comment]
I'm curious as well.  Hesitant to let it run. 
Here's the virustotal scan, lots of other scanner reporting it malicious as well:
  [https://www.virustotal.com/en/file/7202cc4c8d43b8735abd61b53b9be056f0cffe42e5876f3f01947af76d1ab8ed/analysis/]

**Comment by gsxryan** [comment]
I reviewed the commits from the last revision.  Reported it as a False Positive to Avast.  Recommend Closing the issue.

**Comment by cygnusxi** [comment]
Yes this is a false positive, anti virus companies often consider crypto tokens to be "potentially unwanted"
