### ISSUE TITLE
Trojan.Gen.2

### ISSUE THREAD

**Issue by waveboy2u** [cygnusxi/CurecoinSource#23]
My antivirus detects it as being Trojan.Gen.2

**Comment by cygnusxi** [comment]
False positives are common with cryptocurrency clients. Please submit the file to your antivirus company for white listing, or create an exception for it. 
Example of recent case https://www.reddit.com/r/curecoin/comments/7bklei/avast_confirms_curecoin_wallet_as_false_positive/
