### ISSUE TITLE
exe file rejected by antivirus program

### ISSUE THREAD

**Issue by Grizzly7** [cygnusxi/CurecoinSource#26]
Downloaded the EXE file, but Norton Antivirus immediately deleted it and stated that there is a trojan horse inside. Please someone help get rid of it.

**Comment by shadoobie** [comment]
I can recreate this using windows 10 and the latest version of Norton that is given to Xfinity/Comcast users.  Norton thinks curecoin-qt.exe is has a threat name of Trojan.Gen.2.

**Comment by cygnusxi** [comment]
This issue has been reviewed and closed before. You can safely add an exception to the exe file. We are continually working to get white listed with more antivirus software. 
Closed Issues
https://github.com/cygnusxi/CurecoinSource/issues/23
https://github.com/cygnusxi/CurecoinSource/issues/20
