### ISSUE TITLE
src/bignum.h:51:24: error: invalid use of incomplete type 'BIGNUM {aka struct bignum_st}'

### ISSUE THREAD

**Issue by marku89** [cygnusxi/CurecoinSource#28]
incompatible with openssl 

> openssl version
> OpenSSL 1.1.0g  2 Nov 2017

> src/bignum.h:51:24: error: invalid use of incomplete type 'BIGNUM {aka struct bignum_st}'
>  class CBigNum : public BIGNUM

Maybe Dumpicate from bitcoin source 
https://github.com/bitcoin/bitcoin/issues/7086

**Comment by gsxryan** [comment]
Can Confirm. 

I solved this issue with a workaround, installing these packages:

libssl1.0-dev
libssl1.0.2

**Comment by mvehar** [comment]
For Ubuntu 18.04 it worked by downgrading openssl to 1.0.2 -> temporary solution only
https://github.com/BitzenyCoreDevelopers/bitzeny/issues/7#issuecomment-447852356

**Comment by Djhg2000** [comment]
Any update on this?

Such old versions of libssl-dev is no longer available on Debian Sid (and the libssl1.0.2 runtime libraries are only available through the oldstable repository), so this will have to be fixed properly soon.

**Comment by moobsen** [comment]
I  guess these tickets can be merged? https://github.com/cygnusxi/CurecoinSource/issues/28

**Comment by moobsen** [comment]
Seems like a duplicate issue https://github.com/cygnusxi/CurecoinSource/issues/21

**Comment by Djhg2000** [comment]
@moobsen Correct, this does indeed look like a duplicate. I guess I just clicked the first issue matching what I was looking for.

**Comment by cygnusxi** [comment]
#48 has been merged and should fix boost for all 1.7+ versions, please report if there are any issues.
