### ISSUE TITLE
Cannot compile on debian 9.

### ISSUE THREAD

**Issue by riatzukiza** [cygnusxi/CurecoinSource#32]
These are the logs from the `make` command.
https://gist.github.com/anonymous/97cbd2be0f0572b2ce0c1177accf2eec
I'm about to attempt to compile again on a fresh install of ubuntu 16.04

Before compileing I ran the apt install command indicated in the readme to install all nessisary dependencies.

**Comment by WhiteRayne2** [comment]
Getting the same error when compiling on Arch Linux. Switching to libssl 1.0 seems to "fix" the issue...

Change the .pro file like this to see if that works for you too:

`echo "INCLUDEPATH += /usr/include/openssl-1.0" >> "curecoin-qt.pro"`
`echo "LIBS += -L/usr/lib/openssl-1.0 -lcrypto -lz" >> "curecoin-qt.pro"`

**Comment by riatzukiza** [comment]
I would, but I managed to fry out that debian install trying to get AMD
drivers working for FAH and ended up installing ubuntu.

I'll probably be setting up another rig with debian soon, so I will test
this then.

**Comment by djspacewhale** [comment]
same error on Fedora 27, editing the .pro file didn't fix anything...

**Comment by zhangxiangxiao** [comment]
Same as issue #28

**Comment by TheComputerGenie** [comment]
https://github.com/cygnusxi/CurecoinSource#notes

**Comment by gsxryan** [comment]
Another workaround to Installing a Full version of Older OpenSSL, which may be more secure.

I solved this issue by installing these packages:

libssl1.0-dev
libssl1.0.2

**Comment by cygnusxi** [comment]
code has been updated for compatibility - issue closed
