### ISSUE TITLE
starting coin daemon

### ISSUE THREAD

**Issue by vr4dude316** [cygnusxi/CurecoinSource#34]
i believe to have compiled.  how do i start the daemon.  not the same as other coins installed on my yiimp pool

**Comment by gonzalez23** [comment]
M

**Comment by TheComputerGenie** [comment]
'curecoind' builds in 'src' dir; not sure how that's any different from whatever you've bee building, but it's standard for every coin I know of.

**Comment by cygnusxi** [comment]
from CurecoinSource/src
./curecoind
Try joining the discord channel for further help. https://discord.gg/jtztkFZ
