### ISSUE TITLE
Blockchain syncing stalls out with CureCoin Wallet v2.0.0.1

### ISSUE THREAD

**Issue by Hou5e** [cygnusxi/CurecoinSource#37]
CureCoin Wallet v2.0.0.1: The blockchain syncing stalls out when loading in the new 'POS only' section of the blockchain after the v2.0 Hard Fork (to remove the POW component). If you start with the blockchain just before the hard fork, it will sync fine with no real issues. The syncing failure can happen in the initial phase, or when the wallet is open for a long period of time (most likely with a flaky internet connection). The issue happens on both Windows and Linux for me (and MacOS reported by others).

This looks like it might be the code to fix the issue:
https://github.com/Peershares/Peershares/pull/110/commits/ad71a3b1890208c9ef8ea005c76ee18fbf0b6065

The workaround is to install the blockchain before the hard fork (by deleting the blockchain and letting it re-download), or by using the larger installer which contains the blockchain just before the hard fork:
https://github.com/Hou5e/FoldingBrowser/releases/tag/v2.0.0.1

Sample of repeated error messages:
```
received block 3d4d2b4d33d2762bec46
ERROR: CheckProofOfStake() : INFO: check kernel failed on coinstake 7628506e5f982578f02aaed5582c1238ae5bf9420e573400164c5370af1fc4e7, hashProof=000005da6bc09cbbf7caf89c587bb938ea66675bcdfe6163dcf2f455e3d65c7f
WARNING: ProcessBlock(): check proof-of-stake failed for block 3d4d2b4d33d2762bec46638e14f51192623ba83277476f17af2a7a410f3b0db1
received block 6e76c939ed4fb4967d66
ERROR: CheckProofOfStake() : INFO: check kernel failed on coinstake f8274e2554b4d99ea6190592d00c07a61e3b8ff947f216bdd5bd30b9617f2d8a, hashProof=000002d48a8e5c94f7dab8cd7ebcb5f398a3bd80a24bc8bb3d98cd2bed5d8ecb
WARNING: ProcessBlock(): check proof-of-stake failed for block 6e76c939ed4fb4967d668933464e25c2dc793a2426e970242012453f23b242d3
received block bc5150a893b7ccd1a478
ERROR: CheckStakeKernelHash() : min age violation
ERROR: CheckProofOfStake() : INFO: check kernel failed on coinstake 80408a23b223ae19fef2cc3926ae87d4c2afc03169b0c78f66037ecd28ac2ad9, hashProof=0000000000000000000000000000000000000000000000000000000000000000
WARNING: ProcessBlock(): check proof-of-stake failed for block bc5150a893b7ccd1a47841aca3f8dafadeb34bd9bf8dedc2509e6a99f6dbe402
received block b51e646a35d29116061a
ERROR: CheckProofOfStake() : INFO: check kernel failed on coinstake 10e9ef4fd7063ef3ddb9197bdc7c8ca6b6ac75c24d9b549b71d7162beb99980c, hashProof=000005bedb27b4728b88c38f12ba286a7f7efec65afccfa9856d4259793828bf
WARNING: ProcessBlock(): check proof-of-stake failed for block b51e646a35d29116061aef2514a8730ae73e1709f8533182b001233bb9a756ae
```

**Comment by TheComputerGenie** [comment]
Tested ACK
PR submitted:
https://github.com/cygnusxi/CurecoinSource/pull/38

**Comment by TheComputerGenie** [comment]
Upon further testing, those changes do not fix the issue.

The problem is similar, but from a different perspective.
Since each block becomes a checkpoint, the problem arises from receiving the chain tip first, the tip is set as 'pending for sync-checkpoint', and then the proper next block cannot be traced as a descendant because the blocks between are missing.
Basically, you can't get the next block because you don't have the next block.
The "ignore older checkpoint" needs a matching "ignore future checkpoint".

**Comment by Hou5e** [comment]
The fix from Peershares looked like it resolved the sync stall problem on any quick testing with Linux. Except, when the wallet sat closed for over a day, then the sync stall issue would still happen.

**Comment by TheComputerGenie** [comment]
@Hou5e I believe they are 2 separate issues.
As far as I can tell, the latter comes from an issue with marking the chain tip as pending and then creating a loop (of sorts) where you can't back check the tip without older blocks and you can't get older blocks trying to validate the tip.
The concept of the issues are the same, in that IsInitialBlockDownload() needs to be a deciding factor in the decision tree.

**Comment by blackjok3rtt** [comment]
Doesn't actually look like its that hard ... You just need u find the check for this condition and make sure its only happening on connect tip and no where else... thats how I fixed the banning of peers on KMD.... seems much the same.

**Comment by shorttack** [comment]
I am having the same problem as hou5e. I installed version 2.0.0m wallet at end of December and recreated the database (after previous attempts to "continue" from the 1.0 wallet failed.) After days downloading the blockchain database, the wallet ran successfully for several days, receiving Folding@Home transfers daily. 

I am hung at block 26172 for three days. My log looks like hou5e's log posted above.  Glad to provide more log. The curecoin blockchain explorer says my wallet has received transactions daily, but wallet 2.0.0 is stuck at January 4th.

Please advise.

**Comment by Hou5e** [comment]
I found the offending issue. The initial POS validation was failing for POS Min Age still being checked to 30 days after the hardfork, now that it's 4 days.

Details: The error "CheckStakeKernelHash() : min age violation" was being thrown in CheckProofOfStake because the nStakeMinAge variable wasn't being updated for the changes after the hardfork.

The fix was to update this number, about where the Testnet would update this number:
if ( nBestHeight > (int)HF_BLOCK ) nStakeMinAge = 60 * 60 * 24 * 4; // 4 day min stake age hardfork
The testnet testing would have missed this because the testnet settings were updating that value in a good location.

The Peershares fix (https://github.com/Peershares/Peershares/commit/ad71a3b1890208c9ef8ea005c76ee18fbf0b6065) looks good so far with that addition.

These are the modified source files I'm using with both changes combined: [ModifiedFiles.zip](https://github.com/cygnusxi/CurecoinSource/files/2752486/ModifiedFiles.zip)
I will do some more testing, but I think this fixes the issue. PR: #43

**Comment by cygnusxi** [comment]
Client updated to v2.0.0.2 with this fix, thanks @Hou5e

**Comment by shorttack** [comment]
Thanks very much. Can you make a Mac OSX version or point me to how to make one?

Pete

**Comment by shorttack** [comment]
I had no problems this morning updating the block chain on my Mac with 2.0.0.2.

Pete
