### ISSUE TITLE
Feature Request: Automatic Backup

### ISSUE THREAD

**Issue by IIAIronWolf** [cygnusxi/CurecoinSource#52]
Please add the ability to run an automated wallet backup. I want to backup my wallet daily to my network drive, in case something happens to the machine running Curecoin Wallet.

**Comment by Nuitari** [comment]
You only need a copy of your private key to restore your wallet anywhere. Its part of how cryptocurrencies are built

**Comment by IIAIronWolf** [comment]
Still a n00b. Thanks for the info!
