### ISSUE TITLE
Wallet crashes at encryption

### ISSUE THREAD

**Issue by SMPepper** [cygnusxi/CurecoinSource#56]
I run the wallet on an Ubuntu 18.04 LTS after installing on 20th of May 2020. I start the wallet from the terminal. When I try to encrypt my wallet, the wallet crashes and I read in the terminal: "Memory access error (memory image written)". When I restart the wallet, it is still unencrypted.

**Comment by Nuitari** [comment]
Can you try again with the latest version of the source code?

**Comment by SMPepper** [comment]
Great - it works and the wallet is now encrypted. Thanks a lot for your fast support!
