### ISSUE TITLE
Wallet not building on Linux

### ISSUE THREAD

**Issue by aladar42** [cygnusxi/CurecoinSource#61]
I assume the project has been abandoned, but just in case:

the wallet doesnt build on Linux anymore, due to a new Boost update.

src/qt/clientmodel.cpp: In member function ‘void ClientModel::subscribeToCoreSignals()’:
src/qt/clientmodel.cpp:193:100: error: ‘_1’ was not declared in this scope
  193 | onsChanged.connect(boost::bind(NotifyNumConnectionsChanged, this, _1));
      |                                                                   ^~

src/qt/clientmodel.cpp:193:100: note: suggested alternatives:
In file included from /usr/include/boost/mpl/aux_/include_preprocessed.hpp:37,
                 from /usr/include/boost/mpl/placeholders.hpp:43,
                 from /usr/include/boost/iterator/iterator_categories.hpp:16,
                 from /usr/include/boost/iterator/advance.hpp:11,
                 from /usr/include/boost/next_prior.hpp:25,
                 from /usr/include/boost/thread/futures/wait_for_any.hpp:20,
                 from /usr/include/boost/thread/future.hpp:41,
                 from /usr/include/boost/thread.hpp:24,
                 from src/util.h:21,
                 from src/alert.h:13,
                 from src/qt/clientmodel.cpp:7:
/usr/include/boost/mpl/aux_/preprocessed/gcc/placeholders.hpp:29:16: note:   ‘mpl_::_1’
   29 | typedef arg<1> _1;
      |                ^~
In file included from /usr/include/qt/QtCore/qhashfunctions.h:48,
                 from /usr/include/qt/QtCore/qlist.h:47,
                 from /usr/include/qt/QtCore/qobject.h:49,
                 from /usr/include/qt/QtCore/QObject:1,
                 from src/qt/clientmodel.h:4,
                 from src/qt/clientmodel.cpp:1:
/usr/include/c++/10.2.0/functional:221:34: note:   ‘std::placeholders::_1’
  221 |     extern const _Placeholder<1> _1;
      |                                  ^~
In file included from /usr/include/boost/mpl/aux_/include_preprocessed.hpp:37,
                 from /usr/include/boost/mpl/placeholders.hpp:43,
                 from /usr/include/boost/iterator/iterator_categories.hpp:16,
                 from /usr/include/boost/iterator/advance.hpp:11,
                 from /usr/include/boost/next_prior.hpp:25,
                 from /usr/include/boost/thread/futures/wait_for_any.hpp:20,
                 from /usr/include/boost/thread/future.hpp:41,
                 from /usr/include/boost/thread.hpp:24,
                 from src/util.h:21,
                 from src/alert.h:13,
                 from src/qt/clientmodel.cpp:7:
/usr/include/boost/mpl/aux_/preprocessed/gcc/placeholders.hpp:29:16: note:   ‘mpl_::_1’
   29 | typedef arg<1> _1;
      |                ^~
In file included from /usr/include/boost/bind/bind.hpp:2335,
                 from /usr/include/boost/thread/detail/thread.hpp:33,
                 from /usr/include/boost/thread/thread_only.hpp:22,
                 from /usr/include/boost/thread/thread.hpp:12,
                 from /usr/include/boost/thread.hpp:13,
                 from src/util.h:21,
                 from src/alert.h:13,
                 from src/qt/clientmodel.cpp:7:
/usr/include/boost/bind/placeholders.hpp:58:38: note:   ‘boost::placeholders::_1’
   58 | BOOST_STATIC_CONSTEXPR boost::arg<1> _1;
      |                                      ^~
In file included from /usr/include/boost/mpl/aux_/include_preprocessed.hpp:37,
                 from /usr/include/boost/mpl/placeholders.hpp:43,
                 from /usr/include/boost/iterator/iterator_categories.hpp:16,
                 from /usr/include/boost/iterator/advance.hpp:11,
                 from /usr/include/boost/next_prior.hpp:25,
                 from /usr/include/boost/thread/futures/wait_for_any.hpp:20,
                 from /usr/include/boost/thread/future.hpp:41,
                 from /usr/include/boost/thread.hpp:24,
                 from src/util.h:21,
                 from src/alert.h:13,
                 from src/qt/clientmodel.cpp:7:
/usr/include/boost/mpl/aux_/preprocessed/gcc/placeholders.hpp:29:16: note:   ‘mpl_::_1’
   29 | typedef arg<1> _1;
      |                ^~
src/qt/clientmodel.cpp:194:86: error: ‘_2’ was not declared in this scope
  194 | ifyAlertChanged.connect(boost::bind(NotifyAlertChanged, this, _1, _2));
      |                                                                   ^~

src/qt/clientmodel.cpp:194:86: note: suggested alternatives:
In file included from /usr/include/boost/mpl/aux_/include_preprocessed.hpp:37,
                 from /usr/include/boost/mpl/placeholders.hpp:43,
                 from /usr/include/boost/iterator/iterator_categories.hpp:16,
                 from /usr/include/boost/iterator/advance.hpp:11,
                 from /usr/include/boost/next_prior.hpp:25,
                 from /usr/include/boost/thread/futures/wait_for_any.hpp:20,
                 from /usr/include/boost/thread/future.hpp:41,
                 from /usr/include/boost/thread.hpp:24,
                 from src/util.h:21,
                 from src/alert.h:13,
                 from src/qt/clientmodel.cpp:7:

etc.

**Comment by vgmoose** [comment]
Looks like #62 solves this problem

**Comment by altruios** [comment]
+1 for visibility. Linux user here.

please see us.

**Comment by sjneph** [comment]
Pull request 62 has been merged, and this problem should be resolved.
