### ISSUE TITLE
synccheckpoint = 0 ?

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [cygnusxi/CurecoinSource#7]
Why is there no higher synccheckpoint made yet ?

Admittedly, the 145k blocks is quite a low amount, but having a synccheckpoint other than from 2014 April (A) could help increase security for CureCoin 
(e.g. people might not land immediately on a fork, ...)

Interestingly, the doc here (B) says there should be checkpoints. Which is probably referring to this (C) ? 

(A) checkable with: getcheckpoint debug command 
I see only the 00000ce427729d5393dbf9f464e7a1d2c039e393e881f93448516b1530b688fc with height 0 from https://github.com/cygnusxi/CurecoinSource/commit/4a425dc60cad1475fa674b157d51951e5686a60e

used cure client: 0.1.3.3, linux, and I am in sync with blockchain

(B) https://github.com/cygnusxi/CurecoinSource/blob/master/UPDATE
(C) https://github.com/cygnusxi/CurecoinSource/commit/4a425dc60cad1475fa674b157d51951e5686a60e

**Comment by cygnusxi** [comment]
This is the same behavior as current peercoin as of 12/9/16 which curecoin is heavily based off. You can see the checkpoints working via the gui on sync http://i.imgur.com/3hEmumI.png .
